### ISSUE TITLE
wish to add in right-click menu of chat frame and block instantly

### ISSUE THREAD

**Issue by nkr-404-NotFound** [funkydude/BadBoy_Ignore#4]
for now i need to run /badboy and select the ad-users to block them.
can we add a menu in right-click menu of chat frame to block user instantly  ?
thankyou

**Comment by funkydude** [comment]
Probably not.

**Comment by nkr-404-NotFound** [comment]
Okay
thanks for your reply

发送自 Windows 10 版邮件应用

发件人: funkydude
发送时间: 2018年1月3日 23:55
收件人: funkydude/BadBoy_Ignore
抄送: TongChengchao; Author
主题: Re: [funkydude/BadBoy_Ignore] wish to add in right-click menu of chatframe and block instantly (#4)

Probably not.
