### ISSUE TITLE
badboy_ignore also blockes guildads, plugin for guildads notinstalled

### ISSUE THREAD

**Issue by tasimi** [funkydude/BadBoy_Ignore#8]
i think this is not intended. just wanted the boosting spam to go aways. the plugin for guild adds is not installed. as soon as i disable the ignore plugin the guild add is back. the blocked spam via "trigger words" is still blocked. found no options to turn guild adds on/off

**Comment by funkydude** [comment]
BadBoy_Ignore is for blocking people... If you want to see chat from a person, don't block them?

**Comment by tasimi** [comment]
oh. did not metion this: there are no players blocked

**Comment by funkydude** [comment]
This addon filters by name, not by chat message. What you're describing is not possible and you can verify this easily by installing BadBoy_History and seeing what's removed.
